### ISSUE TITLE
Нет реализации меню сайта

### ISSUE THREAD

**Issue by russo-turista** [basilred/spirit8#7]
Меню сайта нефункциональна, как следствие  реализована навигация по сайту. При нажатии соответствующий пункт меню, необходимо показывать нужный блок сайта. Желательно реализовать с анимацией прокрутки.

**Comment by basilred** [comment]
Реализовано без анимации прокрутки. Анимация опционально может быть добавлена в будущем отдельным issue #12  как необязательное улучшение поведения.
