### ISSUE TITLE
В меню в блоке "TAKE A LOOK AT OUR WORK"

### ISSUE THREAD

**Issue by russo-turista** [basilred/spirit8#8]
Как мне кажется меню с писком AllWeb | DesignMobile | Design | Photography должно реагировать на наведение курсора мишки, т.к. не совсем ясно что оно вообще функционально (а не статически указывает текущий список)

**Comment by basilred** [comment]
@russo-turista, что конкретно ты имеешь ввиду? Изменение вида курсора при ховере на меню?

**Comment by russo-turista** [comment]
Либо изменение вида курсора, но лучше изменение цвета текста в меню

**Comment by basilred** [comment]
Готово https://github.com/basilred/spirit8/commit/66bcb5c532004e521264aea34960dd670c75a167
